import type { Locale } from "../database/repositories.js";
const pt={
start:"<b>{bot}</b> está online.\n\nBaixo mídias de links, crio pacotes de figurinhas, traduzo textos, mostro o clima e tenho recursos para grupos.",
help:`<b>Comandos do {bot}</b>\n\n<b>Downloads</b>\n/dl &lt;link&gt; — baixa mídia\n/sdl &lt;link&gt; — alias\n/ytdl &lt;link&gt; — vídeo ou áudio do YouTube\n\n<b>Figurinhas</b>\n/kang [emoji] — adiciona a mídia respondida\n/newpack [título] — cria um pacote\n/mypacks — lista pacotes\n/switch — troca o padrão\n/delpack — exclui um pacote\n/getsticker — exporta uma figurinha\n\n<b>Utilidades</b>\n/afk [motivo] ou brb [motivo]\n/weather &lt;cidade&gt; ou /clima\n/tr &lt;idioma&gt; &lt;texto&gt;\n/slap — responda alguém\n/id\n/ping\n\n<b>Administração</b>\n/config\n/disable &lt;comando&gt;\n/enable &lt;comando&gt;\n/disabled\n/disableable`,
privacy:"<b>Privacidade</b>\n\nO bot salva IDs, nomes públicos, configurações, status AFK e referências de pacotes. Mídias são processadas temporariamente e os arquivos locais são removidos após o envio. O Redis guarda cache e bloqueios com expiração.",
onlyGroups:"Este comando funciona apenas em grupos.",adminOnly:"Apenas administradores do grupo podem usar esta opção.",ownerOnly:"Este comando é restrito ao proprietário.",commandDisabled:"O comando <code>/{command}</code> está desativado neste grupo.",invalidCommand:"Comando inválido ou protegido.",
configTitle:"<b>Configurações deste grupo</b>\n\nToque nos botões para alterar os recursos.",saved:"Configuração atualizada.",mediaAuto:"Download automático",mediaCaption:"Legendas",mediaErrors:"Mostrar erros",deleteSource:"Apagar mensagem original",language:"Idioma",back:"Voltar",enabled:"Ativado",disabled:"Desativado",
disableUsage:"Uso: <code>/disable comando</code>",enableUsage:"Uso: <code>/enable comando</code>",commandDisabledOk:"O comando <code>/{command}</code> foi desativado.",commandEnabledOk:"O comando <code>/{command}</code> foi ativado.",commandAlreadyDisabled:"Esse comando já estava desativado.",commandAlreadyEnabled:"Esse comando já estava ativado.",noDisabledCommands:"Nenhum comando está desativado.",disabledCommands:"<b>Comandos desativados</b>\n{commands}",disableableCommands:"<b>Comandos desativáveis</b>\n{commands}",
afkSet:"💤 <b>{name}</b> agora está AFK.\nMotivo: <code>{reason}</code>",afkBack:"👋 <b>{name}</b> voltou após {duration}.",afkMention:"💤 <b>{name}</b> está AFK há {duration}.\nMotivo: <code>{reason}</code>",
downloadNeedUrl:"Envie um link ou responda a uma mensagem que contenha um link.",downloadUnsupported:"Esse domínio não está habilitado.",downloadStarted:"⏳ Processando mídia…",downloadQueued:"⏳ Seu download entrou na fila…",downloadCooldown:"Aguarde {seconds}s antes de outro download.",downloadInProgress:"Esse link já está sendo processado.",downloadTooLong:"A mídia excede o limite de duração.",downloadNoMedia:"Não encontrei mídia utilizável.",downloadFailed:"Não consegui baixar a mídia. Código: <code>{code}</code>",downloadTooLarge:"Arquivo maior que {mb} MB.",ytdlChoose:"<b>{title}</b>\n{meta}\nEscolha o formato:",video:"Vídeo",audio:"Áudio",expiredButton:"Este botão expirou.",buttonOwnerOnly:"Somente quem pediu pode usar este botão.",
stickerReplyRequired:"Responda a uma figurinha, foto, imagem, vídeo ou animação.",stickerPreparing:"🛠 Preparando a figurinha…",stickerAdded:"✅ Figurinha adicionada a <a href=\"https://t.me/addstickers/{pack}\">{title}</a>.",stickerPackCreated:"✅ Pacote criado: <a href=\"https://t.me/addstickers/{pack}\">{title}</a>.",stickerPackFull:"O pacote atual estava cheio; criei outro automaticamente.",stickerUnsupported:"Esse tipo de arquivo não pode virar figurinha.",stickerFailed:"Não consegui criar a figurinha. Código: <code>{code}</code>",noPacks:"Você ainda não tem pacotes. Use /kang respondendo a uma mídia.",packsTitle:"<b>Seus pacotes</b>\n{packs}",choosePack:"Escolha o pacote padrão:",packSwitched:"✅ Padrão alterado para <b>{title}</b>.",chooseDeletePack:"Escolha o pacote a excluir:",confirmDeletePack:"Excluir definitivamente <b>{title}</b>?",packDeleted:"Pacote excluído.",packNotFound:"Pacote não encontrado.",
weatherUsage:"Uso: <code>/weather Porto Alegre</code>",weatherChoose:"Escolha a localização:",weatherDetails:"<b>{location}</b>\n{emoji} {condition}\n🌡 {temperature}°C · sensação {feels}°C\n💧 Umidade: {humidity}%\n💨 Vento: {wind} km/h",translateUsage:"Uso: <code>/tr pt texto</code> ou responda com <code>/tr pt</code>.",translation:"<b>{source}</b> → <b>{target}</b>\n<code>{text}</code>",slapNeedReply:"Use /slap respondendo a outra pessoa.",ping:"🏓 Pong! <code>{ms} ms</code>",idInfo:"<b>IDs</b>\nUsuário: <code>{userId}</code>\nChat: <code>{chatId}</code>",
announceUsage:"Uso: <code>/announce users|groups|all mensagem</code>",announcePreview:"<b>Prévia</b>\nPúblico: <code>{target}</code>\n\n{message}",confirm:"Confirmar",cancel:"Cancelar",cancelled:"Operação cancelada.",announceDone:"Anúncio concluído.\n✅ Enviados: <code>{sent}</code>\n❌ Falhas: <code>{failed}</code>",stats:"<b>Estatísticas</b>\nUsuários: <code>{users}</code>\nGrupos: <code>{groups}</code>",genericError:"Erro inesperado. Código: <code>{code}</code>",addToGroup:"Adicionar a um grupo",commands:"Comandos",privacyButton:"Privacidade",cached:"⚡ Enviado do cache."
};
const en:typeof pt={...pt,
start:"<b>{bot}</b> is online.\n\nI download media, create sticker packs, translate text, show weather and provide group utilities.",
onlyGroups:"This command only works in groups.",adminOnly:"Only group administrators can use this option.",ownerOnly:"This command is owner-only.",downloadNeedUrl:"Send a link or reply to a message containing one.",downloadUnsupported:"This domain is not enabled.",downloadStarted:"⏳ Processing media…",downloadQueued:"⏳ Your download was queued…",downloadCooldown:"Wait {seconds}s before another download.",downloadInProgress:"This link is already being processed.",downloadTooLong:"The media exceeds the duration limit.",downloadNoMedia:"No usable media was found.",downloadFailed:"Download failed. Code: <code>{code}</code>",stickerReplyRequired:"Reply to a sticker, photo, image, video, or animation.",weatherUsage:"Usage: <code>/weather London</code>",weatherChoose:"Choose a location:",translateUsage:"Usage: <code>/tr en text</code> or reply with <code>/tr en</code>.",slapNeedReply:"Use /slap while replying to someone.",addToGroup:"Add to a group",commands:"Commands",privacyButton:"Privacy"};
export type TranslationKey=keyof typeof pt;export type TranslationParams=Record<string,string|number|boolean>;
const dictionaries:Record<Locale,typeof pt>={pt_BR:pt,en_US:en};
export function translate(locale:Locale,key:TranslationKey,params:TranslationParams={}){let text=dictionaries[locale][key]??pt[key];for(const[k,v]of Object.entries(params))text=text.replaceAll(`{${k}}`,String(v));return text;}
