import { copyFile,rename,stat } from "node:fs/promises";import { basename,dirname,extname,join,parse } from "node:path";import { execa } from "execa";import { fileTypeFromFile } from "file-type";import sharp from "sharp";import { env } from "../../config/env.js";import { logger } from "../../config/logger.js";import type { MediaKind,PreparedMediaItem } from "./types.js";
const photos=new Set([".jpg",".jpeg",".png",".webp",".avif"]),videos=new Set([".mp4",".mov",".mkv",".webm",".m4v",".gif"]),audios=new Set([".mp3",".m4a",".aac",".ogg",".opus",".wav",".flac"]);
async function kind(p:string):Promise<MediaKind>{const d=await fileTypeFromFile(p).catch(()=>undefined),m=d?.mime??"",e=extname(p).toLowerCase();if(m.startsWith("image/")&&m!=="image/gif")return"photo";if(m.startsWith("video/")||m==="image/gif")return"video";if(m.startsWith("audio/"))return"audio";if(photos.has(e))return"photo";if(videos.has(e))return"video";if(audios.has(e))return"audio";return"document";}
const size=(p:string)=>stat(p).then(s=>s.size);
async function image(input:string){const out=join(dirname(input),`${parse(input).name}-telegram.jpg`);for(const q of[88,78,68,58,48,38]){await sharp(input).rotate().resize({width:4096,height:4096,fit:"inside",withoutEnlargement:true}).jpeg({quality:q,mozjpeg:true}).toFile(out);if(await size(out)<=env.MAX_UPLOAD_BYTES)return out;}return out;}
async function duration(p:string){const r=await execa(env.FFPROBE_BINARY,["-v","error","-show_entries","format=duration","-of","default=noprint_wrappers=1:nokey=1",p],{timeout:30000});const n=Number(r.stdout.trim());return Number.isFinite(n)&&n>0?n:1;}
async function video(input:string){const out=join(dirname(input),`${parse(input).name}-telegram.mp4`),dur=await duration(input),bits=Math.max(2e6,env.MAX_UPLOAD_BYTES*8*.92),ab=96000,vb=Math.max(180000,Math.floor(bits/dur-ab));await execa(env.FFMPEG_BINARY,["-y","-i",input,"-map_metadata","-1","-vf","scale='min(1920,iw)':-2:force_original_aspect_ratio=decrease,format=yuv420p","-c:v","libx264","-preset","veryfast","-b:v",String(vb),"-maxrate",String(Math.floor(vb*1.25)),"-bufsize",String(vb*2),"-c:a","aac","-b:a","96k","-movflags","+faststart",out],{timeout:env.DOWNLOAD_TIMEOUT_SECONDS*1000});return out;}
async function audio(input:string){const out=join(dirname(input),`${parse(input).name}-telegram.mp3`);await execa(env.FFMPEG_BINARY,["-y","-i",input,"-map_metadata","-1","-vn","-c:a","libmp3lame","-b:a","128k",out],{timeout:env.DOWNLOAD_TIMEOUT_SECONDS*1000});return out;}
export async function prepareMediaFiles(paths:string[]):Promise<PreparedMediaItem[]>{const out:PreparedMediaItem[]=[];for(const original of paths){let k=await kind(original),p=original,e=extname(p).toLowerCase();if(k==="video"&&e!==".mp4")p=await video(p);if(k==="audio"&&e!==".mp3")p=await audio(p);if(k==="photo"&&!['.jpg','.jpeg','.png'].includes(e))p=await image(p);let s=await size(p);if(s>env.MAX_UPLOAD_BYTES){p=k==="photo"?await image(p):k==="video"?await video(p):k==="audio"?await audio(p):p;s=await size(p);}if(s>env.MAX_UPLOAD_BYTES){logger.warn({p,s},"Arquivo grande");continue;}const safe=join(dirname(p),basename(p).replace(/[^a-zA-Z0-9._-]/g,"_"));if(safe!==p)try{await rename(p,safe);p=safe;}catch{await copyFile(p,safe);p=safe;}k=await kind(p);out.push({path:p,kind:k,filename:basename(p),size:s});}return out;}
