import { mkdtemp,readdir,stat,writeFile,readFile } from "node:fs/promises";import { tmpdir } from "node:os";import { basename,extname,join } from "node:path";import { execa } from "execa";import { env } from "../../config/env.js";import { logger } from "../../config/logger.js";import type { DownloadMode,MediaMetadata } from "./types.js";
interface Info{id?:string;title?:string;description?:string;uploader?:string;channel?:string;uploader_id?:string;duration?:number;webpage_url?:string;original_url?:string;thumbnail?:string;extractor_key?:string;extractor?:string;entries?:Info[];}
let cookiePromise:Promise<string|undefined>|undefined;
async function cookieFile(){const b64=env.YTDLP_COOKIES_B64;if(!b64)return undefined;cookiePromise??=(async()=>{const p=join(tmpdir(),"esqueletops-nova-cookies.txt");await writeFile(p,Buffer.from(b64,"base64"),{mode:0o600});return p;})();return cookiePromise;}
async function common(){const a=["--no-warnings","--no-progress","--newline","--retries","3","--fragment-retries","3","--socket-timeout","20","--concurrent-fragments","4","--no-check-certificates"];const c=await cookieFile();if(c)a.push("--cookies",c);if(env.YTDLP_PROXY)a.push("--proxy",env.YTDLP_PROXY);return a;}
function metadata(i:Info,url:string):MediaMetadata{const s=i.entries?.find(Boolean)??i;return{id:s.id,title:s.title,description:s.description,uploader:s.uploader??s.channel,uploaderId:s.uploader_id,duration:s.duration,webpageUrl:s.webpage_url??i.webpage_url??i.original_url??url,thumbnail:s.thumbnail,extractor:s.extractor_key??s.extractor};}
export async function probeMedia(url:string){const r=await execa(env.YTDLP_BINARY,[...await common(),"--dump-single-json","--skip-download","--playlist-end","1",url],{timeout:env.DOWNLOAD_TIMEOUT_SECONDS*1000,maxBuffer:20*1024*1024});return metadata(JSON.parse(r.stdout),url);}
async function walk(root:string):Promise<string[]>{const out:string[]=[];for(const e of await readdir(root,{withFileTypes:true})){const p=join(root,e.name);e.isDirectory()?out.push(...await walk(p)):out.push(p);}return out;}
export async function downloadMedia(url:string,mode:DownloadMode){const directory=await mkdtemp(join(tmpdir(),"esqueletops-nova-media-"));const template=join(directory,"%(playlist_index|)s%(id)s-%(title).80B.%(ext)s");const a=[...await common(),"--yes-playlist","--playlist-end",String(env.MAX_MEDIA_ITEMS),"--restrict-filenames","--trim-filenames","120","--output",template,"--write-info-json","--max-filesize",`${Math.ceil(env.MAX_UPLOAD_MB*2)}M`];if(mode==="audio")a.push("--extract-audio","--audio-format","mp3","--audio-quality","0");else a.push("--format","bv*[height<=1080][ext=mp4]+ba[ext=m4a]/bv*[height<=1080]+ba/b[height<=1080]/best","--merge-output-format","mp4");a.push(url);logger.debug({url,mode},"yt-dlp");await execa(env.YTDLP_BINARY,a,{timeout:env.DOWNLOAD_TIMEOUT_SECONDS*1000,maxBuffer:50*1024*1024});const all=await walk(directory);let m:MediaMetadata={webpageUrl:url};const info=all.find(p=>p.endsWith(".info.json"));if(info)try{m=metadata(JSON.parse(await readFile(info,"utf8")),url);}catch{}else try{m=await probeMedia(url);}catch{}const ignored=new Set([".json",".part",".ytdl",".temp"]);const files:string[]=[];for(const p of all){if(p.endsWith(".info.json")||ignored.has(extname(p).toLowerCase()))continue;const s=await stat(p);if(s.isFile()&&s.size>0)files.push(p);}files.sort((a,b)=>basename(a).localeCompare(b,undefined,{numeric:true}));return{directory,files:files.slice(0,env.MAX_MEDIA_ITEMS),metadata:m};}
